# Generated by Django 5.1.6 on 2025-03-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_accountinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountinfo',
            options={'verbose_name': '用户账号信息'},
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table='t_account',
        ),
    ]
